
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-10
owner: ucsb-cs156-f25
repo_name: team01-f25-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjU1OTMwMzMy","is_bot":false,"login":"saanvi25","name":"Saanvi Pabbichetty"},"headRefName":"Saanvi-DELETEUCSBOrganization","number":72,"title":"UCSB Organization DELETE endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/72"},{"author":{"id":"MDQ6VXNlcjU1OTMwMzMy","is_bot":false,"login":"saanvi25","name":"Saanvi Pabbichetty"},"headRefName":"Saanvi-PUTUCSBOrganization","number":71,"title":"UCSBOrganization PUT (edit) endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/71"},{"author":{"id":"MDQ6VXNlcjU1OTMwMzMy","is_bot":false,"login":"saanvi25","name":"Saanvi Pabbichetty"},"headRefName":"Saanvi-GETUCSBOrganization","number":67,"title":"UCSBOrganization GET(show) endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/67"},{"author":{"id":"MDQ6VXNlcjU1OTMwMzMy","is_bot":false,"login":"saanvi25","name":"Saanvi Pabbichetty"},"headRefName":"Saanvi-UCSBOrganizationController","number":66,"title":"UCSB Organization Controller GET and POST with tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/66"},{"author":{"id":"MDQ6VXNlcjU1OTMwMzMy","is_bot":false,"login":"saanvi25","name":"Saanvi Pabbichetty"},"headRefName":"Saanvi-UCSBOrganization-create-db","number":65,"title":"Add UCSBOrganization entity, repository, and database migration","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/65"},{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-HelpRequest-delete","number":54,"title":"HelpRequest add DELETE endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/54"},{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-helprequest-put","number":51,"title":"HelpRequest add PUT endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/51"},{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-helprequest-get","number":50,"title":"HelpRequest add GET(show) endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/50"}]
