
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-10
owner: ucsb-cs156-f25
repo_name: team01-f25-10
pull_requests: [{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-delete-Articles","number":76,"title":"Charlie delete articles","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/76"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-edit-Articles","number":75,"title":"Charlie edit articles","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/75"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-get-single-endpoint-Articles","number":74,"title":"Charlie get single endpoint articles","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/74"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-Articles-create-Controller-Get-Post","number":73,"title":"Charlie articles create controller get post","url":"https://github.com/ucsb-cs156-f25/team01-f25-10/pull/73"}]
